014/img cap component
samuraijane/leopardy pull request #59
Opened 2023-06-30 01:02 UTC by Henryesc

2023-07-01 14:25 UTC, christinab980 reviewed
+1

2023-07-01 14:35 UTC, samuraijane requested changes
Please create a reusable component that holds the repeated structure.

2023-10-04 23:16 UTC, samuraijane approved these changes
+1

2023-10-04 23:22 UTC, christinab980 approved these changes
+1

2023-10-04 23:24 UTC, merged